# Scikit-Learn 맛보기

### 1. 데이터 로딩 후 데이터 확인

In [5]:
from sklearn.datasets import load_iris
iris = load_iris()

In [6]:
# X, y
iris_data = iris.data       # X ## iris.data는 Iris 데이터 세트에서 feature만으로 된 데이터를 numpy로 가지고 있습니다
iris_label = iris.target     # y ### iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있습니다.

In [7]:
iris_data.shape, iris_label.shape

((150, 4), (150,))

In [8]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [9]:
# feature data는 x에 해당됨
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
# Target data 는 y에 해당됨
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [12]:
import pandas as pd

In [13]:
# Iris data => DataFrame으로 변환
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [14]:
iris_df['species'] = iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  species  
0      0        0  
1      0        0  
2      0        0  
3      0        0  
4      0        0

### 2. 학습용 데이터와 테스트용 데이터 분리

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.2, random_state=2021
)
#  test_size 입력 값의 비율로 데이터를 쉽게 분할

In [21]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [22]:
y_test

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 1, 1, 0, 1, 1, 2,
       2, 0, 2, 1, 1, 1, 0, 0])

# 결정 트리(Decision Tree) 알고리즘

### 3. 머신러닝 알고리즘을 적용해 학습

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [24]:
# 객체 생성 --> 모델 생성
dt_clf = DecisionTreeClassifier(random_state=11)  # 모델 생성시 Hyper-parameter 결정
dt_clf

DecisionTreeClassifier(random_state=11)

In [25]:
# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

### 4. 학습된 모델을 기반으로 테스트 데이터에 대해 예측 수행

예측은 반드시 학습 데이터가 아닌 다른 데이터를 이용하며 일반적으로 테스트 데이터 세트를 이용

→ predict()에 테스트용 피처데이터를 입력하여 예측 값을 반환

In [26]:
# 예측값
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

### 5. 예측값과 실제값을 비교해 모델의 성능을 평가
accuracy_score(실제 레이블 세트, 예측 레이블 세트) : 정확도를 측정하기 위한 사이킷런의 함수

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
# 정확도 평가
score = accuracy_score(y_test, pred)
score

0.9333333333333333

In [31]:
print(f'결정트리 예측 정확도: {score:.4f}')

결정트리 예측 정확도: 0.9333


In [29]:
y_test

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 1, 1, 0, 1, 1, 2,
       2, 0, 2, 1, 1, 1, 0, 0])

In [30]:
pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 1, 1, 0, 1, 1, 2,
       1, 0, 1, 1, 1, 1, 0, 0])

## 정리 : 예측 프로세스

(1) 데이터 세트 분리 : 학습데이터와 테스트데이터로 분리 (train_test_split())

(2) 모델 학습 : 학습데이터를 기반으로 머신러닝 알고리즘을 적용하여 모델을 학습

(3) 예측 수행 : 학습된 모델을 이용하여 테스트 데이터의 분류를 예측

(4) 평가 : 예측 결과값과 실제 결과값을 비교하여 모델 성능을 평가

In [55]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

In [56]:
sv_clf = SVC(random_state=2021)
dt_clf = DecisionTreeClassifier(random_state=11)
lr_clf = LogisticRegression(random_state=2021)

In [57]:
#SVM
sv_clf.fit(X_train, y_train)

SVC(random_state=2021)

In [58]:
sv_clf.score(X_test, y_test)

1.0